apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vscode-remote.fullname" . }}
  labels:
    {{- include "vscode-remote.labels" . | nindent 4 }}
data:
  {{- $size := default 10 (include "resource-mb" .Values.docker.persistence.size) }}
  daemon.json: |-
    {
      "features": {
        "buildkit" : true
      },
      "builder": {
        "gc": {
          "enabled": true,
          "defaultKeepStorage": "{{ int64 (divf $size 2) }}MB"
        }
      },
      "hosts": ["unix:///var/run/docker.sock","tcp://127.0.0.1:2376"],
      "default-address-pools": [
        {"base": "198.18.9.0/16","size": 24}
      ],
      "mtu": 1280,
      "log-level": "warn"
    }
  buildkitd.toml: |-
    root = "/var/lib/buildkit"
    debug = false

    [grpc]
      address = [ "unix:///run/buildkit/buildkitd.sock","tcp://127.0.0.1:2376" ]
      uid = 0
      gid = 0

    [worker.containerd]
      enabled = false

    [worker.oci]
      enabled = true
      max-parallelism = 4

      gc = true
      gckeepstorage = "{{ int64 (divf $size 2) }}MB"
    [[worker.oci.gcpolicy]]
      keepBytes = "{{ int64 (divf $size 3) }}MB"
      keepDuration = "24h"
      filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
    [[worker.oci.gcpolicy]]
      all = true
      keepBytes = "{{ int64 (divf $size 2) }}MB"
