apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscode-remote.fullname" . }}
  labels:
    {{- include "vscode-remote.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vscode-remote.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/envs: {{ include "vscode-remote.profileScript" . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vscode-remote.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vscode-remote.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: kubeconfig
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/sh']
          args:
            - -ec
            - |
              install -m 0600 -o vscode -g vscode /home/vscode/.ssh/kubeconfig-orig /home/vscode/.kubeconfig/kubeconfig
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: kubeconfig
              mountPath: /home/vscode/.kubeconfig
            - name: ssh
              mountPath: /home/vscode/.ssh
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/usr/sbin/sshd','-D','-e']
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          {{- if .Values.service.sshHostPort }}
              hostPort: {{ .Values.service.sshHostPort }}
          {{- end }}
          {{- if .Values.service.port }}
            - name: service
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          volumeMounts:
          {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
            - name: profile
              mountPath: /etc/profile.d
            - name: workdir
              mountPath: /www
            - name: kubeconfig
              mountPath: /home/vscode/.kubeconfig
            - name: ssh
              mountPath: /home/vscode/.ssh
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
  {{- if not .Values.persistence.enabled }}
        - name: workdir
          emptyDir: {}
  {{- else if .Values.persistence.existingClaim }}
        - name: workdir
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
  {{- else }}
        - name: workdir
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "vscode-remote.fullname" . }}{{- end }}
  {{- end }}
        - name: profile
          secret:
            secretName: {{ include "vscode-remote.fullname" . }}-envs
            items:
            - key: envs.sh
              path: envs.sh
            defaultMode: 292 # 0444
        - name: kubeconfig
          emptyDir:
            medium: Memory
            sizeLimit: "100Ki"
        - name: ssh
          secret:
            secretName: {{ include "vscode-remote.fullname" . }}-ssh
            defaultMode: 256
