{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vscode-remote.fullname" . }}
  labels:
    {{- include "vscode-remote.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vscode-remote.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        {{- toYaml .Values.networkPolicy.from | nindent 8 }}
      ports:
        - protocol: TCP
          port: 22
{{- end }}
