apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vscode-remote.fullname" . }}-envs
  labels:
    {{- include "vscode-remote.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.envs }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vscode-remote.fullname" . }}-ssh
  labels:
    {{- include "vscode-remote.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.sshConfig }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
