apiVersion: v1
kind: Service
metadata:
  name: {{ include "vscode-remote.fullname" . }}
  labels:
    {{- include "vscode-remote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  {{- if .Values.service.port }}
    - port: {{ .Values.service.port }}
      targetPort: service
      protocol: TCP
      name: service
  {{- end }}
  selector:
    {{- include "vscode-remote.selectorLabels" . | nindent 4 }}
