version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "UTC"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "UTC"
    labels:
      - "dependencies"
